### ISSUE TITLE
Can't install Firefox extensions as appears to be corrupt

### ISSUE THREAD

**Issue by levysantanna** [liady/ChatGPT-pdf#55]
Can't install Firefox extensions as appears to be corrupt

**Comment by levysantanna** [comment]
I was trying to install the version 1.3.4

![image](https://user-images.githubusercontent.com/1235238/229142758-a9b6a477-67ba-4a2b-aebe-a73d89b24dfa.png)

**Comment by aspiriine** [comment]
> I was trying to install the version 1.3.4
> 
> ![image](https://user-images.githubusercontent.com/1235238/229142758-a9b6a477-67ba-4a2b-aebe-a73d89b24dfa.png)

did you run the build.sh ?

**Comment by levysantanna** [comment]
not a bug
