### ISSUE TITLE
It stopped working for me

### ISSUE THREAD

**Issue by D-32** [liady/ChatGPT-pdf#6]
It worked for a few hours. Now the buttons don't show up anymore :(
Thanks for your work!

**Comment by gijigae** [comment]
Experiencing the same issue even after updating to the latest release, Version 1.2.1.

**Comment by liady** [comment]
Fixed in 1.3.1:
https://github.com/liady/ChatGPT-pdf/releases/tag/1.3.1

**Comment by gijigae** [comment]
@liady Thank you so much for the update! Confirmed the fix.
