### ISSUE TITLE
Issue with spaces in png & pdf export

### ISSUE THREAD

**Issue by D-32** [liady/ChatGPT-pdf#8]
![image](https://user-images.githubusercontent.com/3063279/205994912-2c9c90a7-a881-4725-b1b8-6d1dbd2d5479.png)

"Share link" export that looks okay: blob:https://chat.openai.com/fc3ae5ca-e4ad-4da2-b6b3-972182de6426

Using version 1.3.1.

**Comment by liady** [comment]
Thanks! This will be fixed in 1.3.2 (thanks to @adrianmarinwork) , will be released in 2 hours.

**Comment by D-32** [comment]
Dope, thanks!

**Comment by liady** [comment]
@D-32 should be fixed in [1.3.2](https://github.com/liady/ChatGPT-pdf/releases/tag/1.3.2)

**Comment by D-32** [comment]
Thanks <3
