### ISSUE TITLE
Version 1.3.2 installation error

### ISSUE THREAD

**Issue by D-32** [liady/ChatGPT-pdf#9]
Can't install 1.3.2:
<img width="557" alt="image" src="https://user-images.githubusercontent.com/3063279/205995574-fc716aed-a112-4901-8cb1-7c99236b396d.png">

**Comment by liady** [comment]
Thanks, it was missing the manifest file, removed it and will re-upload, please use 1.3.1 for now.

**Comment by liady** [comment]
@D-32 Published 1.3.2 again, should work now
